"""add training_experience to users

Revision ID: 7dd1489ff6e8
Revises: bb8b920c14f6
Create Date: 2026-07-06 12:53:05.933462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd1489ff6e8'
down_revision: Union[str, Sequence[str], None] = 'bb8b920c14f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('training_experience', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'training_experience')
    # ### end Alembic commands ###
